### ISSUE TITLE
又用不了了，大佬修一下

### ISSUE THREAD

**Issue by QWERRAO** [9WiSHao/duifene-download#1]

**Comment by 9WiSHao** [comment]
看了眼，只是页面结构稍微改了下，下载链接还是在dom里，原理没变，等有时间我就修

**Comment by QWERRAO** [comment]
谢谢大佬，拯救大学生
&nbsp;


风花雪月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月17日(星期一) 晚上9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [9WiSHao/duifene-download] 又用不了了，大佬修一下 (Issue #1)














 
看了眼，只是页面结构稍微改了下，下载链接还是在dom里，原理没变，等有时间我就修

**Comment by 9WiSHao** [comment]
修了，等油叉那边自动同步吧，你急的话直接把这个仓库的[main.js](https://github.com/9WiSHao/duifene-download/blob/main/main.js) 复制进油猴也能用
